version: "3"
name: tvbox
services:
xiaoya-tvbox:
ports:
- 4567:4567
- 5344:80
environment:
- ALIST_PORT=5344
volumes:
- /project/sandbox/Tvbox-alist/alist:/opt/alist/data
- /project/sandbox/Tvbox-alist/atv:/opt/atv/data
restart: unless-stopped
network_mode: bridge
container_name: xiaoya-tvbox
image: haroldli/xiaoya-tvbox:latest